FROM golang:1.26 AS builder
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 go build -o /vcsim ./test/e2e/cmd/vcsim

FROM gcr.io/distroless/static:nonroot
COPY --from=builder /vcsim /vcsim
ENTRYPOINT ["/vcsim"]
