FROM registry.access.redhat.com/ubi9/ubi as ui

WORKDIR /app
RUN mkdir /app/www && \
     curl -Lo /tmp/agent-latest.tgz https://github.com/kubev2v/migration-planner-ui/releases/download/v0.0.1-test/agent-v0.0.1-test.tgz && \
     tar xf /tmp/agent-latest.tgz -C /app/www

# Builder container
FROM registry.access.redhat.com/ubi9/go-toolset as builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG VERSION
ENV VERSION=${VERSION}

USER 0
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -buildvcs=false \
  -ldflags "-X github.com/kubev2v/migration-planner/internal/agent.version=${VERSION}" \
  -o /planner-agent cmd/planner-agent/main.go

FROM registry.access.redhat.com/ubi9/ubi-micro

WORKDIR /app

COPY --from=builder /planner-agent /app/
COPY --from=ui /app/www/package/dist /app/www

# Use non-root user
RUN chown -R 1001:0 /app
USER 1001

# Run the server
EXPOSE 3333
ENTRYPOINT ["/app/planner-agent"]
