ARG BASE_IMAGE

FROM --platform=linux/amd64 registry.access.redhat.com/ubi9/go-toolset as dlv-builder

USER 0

RUN GOBIN=/app go install github.com/go-delve/delve/cmd/dlv@latest

FROM ${BASE_IMAGE}

COPY --from=dlv-builder /app/dlv /app/dlv

EXPOSE 3443 40000

ENTRYPOINT ["/app/dlv", "--continue", "--listen=:40000", "--headless=true", "--api-version=2", "--accept-multiclient", "exec", "/app/planner-api", "run"]