ARG BASE_IMAGE

FROM --platform=linux/amd64 registry.access.redhat.com/ubi9/go-toolset AS dlv-builder

USER 0

RUN GOBIN=/app go install github.com/go-delve/delve/cmd/dlv@latest

FROM ${BASE_IMAGE}

COPY --from=dlv-builder /app/dlv /app/dlv

EXPOSE 3333 40001

ENTRYPOINT ["/app/dlv", "exec", "/app/planner-agent", "--headless", "--listen=:40001", "--api-version=2", "--accept-multiclient", "--continue", "--"]
