FROM --platform=linux/amd64 registry.access.redhat.com/ubi9/ubi as ui

RUN dnf install -y npm wget

WORKDIR /app
COPY . .
RUN mkdir /app/www && cp -r ./agent-ui/* /app/www
RUN wget -P /app/www/js https://unpkg.com/axios/dist/axios.min.js

WORKDIR /app/www
RUN npm init -y && npm install @patternfly/patternfly
RUN cp -r ./node_modules/@patternfly/patternfly/assets css/
RUN cp -r ./node_modules/@patternfly/patternfly/patternfly.css css/

# Builder container
FROM --platform=linux/amd64 registry.access.redhat.com/ubi9/go-toolset as builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

ARG VERSION
ENV VERSION=${VERSION}

USER 0
RUN CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -buildvcs=false \
  -ldflags "-X github.com/kubev2v/migration-planner/internal/agent.version=${VERSION}" \
  -o /planner-agent cmd/planner-agent/main.go

FROM --platform=linux/amd64 registry.access.redhat.com/ubi9/ubi-minimal

WORKDIR /app

COPY --from=builder /planner-agent /app/
COPY --from=ui /app/www/ /app/www

# Use non-root user
RUN chown -R 1001:0 /app
USER 1001

# Run the server
EXPOSE 3333
ENTRYPOINT ["/app/planner-agent"]
