# Builder container
FROM registry.access.redhat.com/ubi9/go-toolset as builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .

USER 0
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -buildvcs=false -o /planner-api cmd/planner-api/main.go

FROM registry.access.redhat.com/ubi9/ubi-micro

WORKDIR /app

COPY --from=builder /planner-api /app/

# Use non-root user
RUN chown -R 1001:0 /app
USER 1001

# Run the server
EXPOSE 3443
ENTRYPOINT ["/app/planner-api"]
