kind: Service
apiVersion: v1
metadata:
  name: migration-planner-ui
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: migration-planner-ui
