apiVersion: v1
kind: Service
metadata:
  labels:
    app: migration-planner
  name: migration-planner-image
spec:
  ports:
    - name: migration-planner-image
      port: 11443
      protocol: TCP
      targetPort: 11443
  selector:
    app: migration-planner
  type: LoadBalancer
status:
  loadBalancer: {}
