kind: Deployment
apiVersion: apps/v1
metadata:
  name: migration-planner-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: migration-planner-ui
  template:
    metadata:
      labels:
        app: migration-planner-ui
    spec:
      containers:
        - name: migration-planner-ui
          image: quay.io/machacekondra/migration-planner-ui
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
      restartPolicy: Always
