apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mtv-init 
  name:  mtv-init
  namespace: {{ .Values.mtvOperator.subscription.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtv-init
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: mtv-init
    spec:
      containers:
      - image: quay.io/rgolangh/mtv-init
        name: mtv-init
        ports:
          - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mtv-init
  name: mtv-init
  namespace: {{ .Values.mtvOperator.subscription.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  ports:
  - name: 80-8080
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: mtv-init
  type: ClusterIP
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: mtv-init
  namespace: {{ .Values.mtvOperator.subscription.namespace }}
  labels:
    app: mtv-init
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  tls:
    termination: edge
  port:
    targetPort: 8080
  to:
    kind: "Service"
    name: mtv-init
    weight: null
---
apiVersion: v1
kind: Secret
metadata:
  name: vmware-credentials
  namespace: {{ .Values.mtvOperator.subscription.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"


