apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: migration-cluster-day2-installer
  namespace: {{ .Values.mtvOperator.subscription.namespace }}
  annotations:
    securitycontextconstraints.security.openshift.io: anyuid
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: migration-cluster-day2-installer
  namespace: {{ .Values.mtvOperator.subscription.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames:
      - anyuid 
    verbs: ["use"]
  - apiGroups: ["forklift.konveyor.io"]
    resources: ["providers"]
    verbs: ["get", "update", "patch", "list", "delete"]

  - apiGroups: ["operators.coreos.com"]
    resources: ["clusterserviceversions"]
    verbs: ["get", "update", "patch", "list", "delete"]

  - apiGroups: ["lvm.topolvm.io"]
    resources: ["lvmclusters"]
    verbs: ["get", "update", "patch", "list", "delete"]

  - apiGroups: [""]
    resources: ["services"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: migration-cluster-day2-installer-binding
  namespace: {{ .Values.mtvOperator.subscription.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
  - kind: ServiceAccount
    name: migration-cluster-day2-installer
    namespace: {{ .Values.mtvOperator.subscription.namespace }}
roleRef:
  kind: Role
  name: migration-cluster-day2-installer
  apiGroup: rbac.authorization.k8s.io
---

---
# LVM Storage SA
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: migration-cluster-day2-installer
  namespace: {{ .Values.lvmsOperator.subscription.namespace }}
  annotations:
    securitycontextconstraints.security.openshift.io: anyuid
    argocd.argoproj.io/sync-wave: "1"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: migration-cluster-day2-installer
  namespace: {{ .Values.lvmsOperator.subscription.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
rules:
  - apiGroups: ["security.openshift.io"]
    resources: ["securitycontextconstraints"]
    resourceNames:
      - anyuid 
    verbs: ["use"]

  - apiGroups: ["operators.coreos.com"]
    resources: ["clusterserviceversions"]
    verbs: ["get", "update", "patch", "list", "delete"]

  - apiGroups: ["lvm.topolvm.io"]
    resources: ["lvmclusters"]
    verbs: ["get", "update", "patch", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: migration-cluster-day2-installer-binding
  namespace: {{ .Values.lvmsOperator.subscription.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
subjects:
  - kind: ServiceAccount
    name: migration-cluster-day2-installer
    namespace: {{ .Values.lvmsOperator.subscription.namespace }}
roleRef:
  kind: Role
  name: migration-cluster-day2-installer
  apiGroup: rbac.authorization.k8s.io
---

