openapi: 3.0.1
info:
  title: OpenShift Migration Advisor image API
  version: undefined
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: /
paths:
  /api/v1/image-url:
    post:
      tags:
        - image
      description: Generate the OVA image URL
      operationId: GenerateDownloadURL
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required: [id]
              description: Source id
              properties:
                id:
                  type: string
                  format: uuid
      responses:
        "200":
          description: URL to download OVA image
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/presigned-url"
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '../openapi.yaml#/components/schemas/Error'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '../openapi.yaml#/components/schemas/Error'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '../openapi.yaml#/components/schemas/Error'
  /api/v1/image/bytoken/{token}/{name}:
    get:
      tags:
        - image
      description: Get the OVA image via URL
      operationId: getImageByToken
      parameters:
        - name: token
          in: path
          description: User token
          required: true
          schema:
            type: string
        - name: name
          in: path
          description: Image name
          required: true
          schema:
            type: string
      responses:
        "200":
          description: An OVA image
          content:
            application/ovf:
              schema:
                type: string
                format: binary
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '../openapi.yaml#/components/schemas/Error'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '../openapi.yaml#/components/schemas/Error'
        "404":
          description: NotFound
          content:
            application/json:
              schema:
                $ref: '../openapi.yaml#/components/schemas/Error'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '../openapi.yaml#/components/schemas/Error'
    head:
      tags:
        - image
      description: Head the OVA image via URL
      operationId: headImageByToken
      parameters:
        - name: token
          in: path
          description: User token
          required: true
          schema:
            type: string
        - name: name
          in: path
          description: Image name
          required: true
          schema:
            type: string
      responses:
        "200":
          description: An OVA image
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '../openapi.yaml#/components/schemas/Error'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '../openapi.yaml#/components/schemas/Error'
        "404":
          description: NotFound
          content:
            application/json:
              schema:
                $ref: '../openapi.yaml#/components/schemas/Error'
        "500":
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '../openapi.yaml#/components/schemas/Error'
  /health:
    get:
      tags:
        - health
      description: Health check
      operationId: health
      responses:
        "200":
          description: OK

components:
  schemas:
    presigned-url:
      type: object
      required:
        - url
      properties:
        url:
          type: string
          description: Pre-signed URL for downloading the source discovery image.
        expires_at:
          type: string
          format: date-time
          description: Expiration time for the URL token.