// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWQXPzNBD9K5qFo2OnpVx8S6HwZShfv2kIFybDqNbGVmtLYiUnhIz/OyPJSesmpe0M",
	"ZZhpL4ljrfe93bdvnS0UujFaoXIW8i3YosKGh8sLIk3+wpA2SE5iuN2gtbxEfynQFiSNk1pBHuPZ7jgB",
	"tzEIOVhHUpXQdQkQ/tFKQgH5b/s0iy4BQ2hlqVCMWqoPEfFPIwnt79wdAfVn3P9gTjbIlpqYq5DNry+Z",
	"03eoUkhgqanxD4PgDkc+7pBeAj32MP8XwlHkFlL69EKvVa25kKoMUFa3VCAT0hZ6hbRhsuElps92wOMt",
	"9kH65hYLB52PkmqpPZVaFqhsaLXijY+aGF5UyE7TMfSEoXLO2DzL1ut1ysNxqqnM+mdtdjn97uLz7GJ0",
	"mo7TyjW1L9VJV/t0VwbVrJJLx36WZd/GiVhJqylWwSZfppDACsnGfrRK4FIqFD6NNqi4kZDDN+k4PYEE",
	"DHdV0CzjRmarkyxk2cuq7REJf0SFxB2GZl79OumR59eXECAir6l4EPp9L0GM8U1F68612PjshVYOVQDi",
	"xtSyCM9nt9aj7Sb8kMYsyiiFL2Mwf1L4z/0QtW2I+WdxpXhC2/sgRy2GG9Zor5QHOR2PX1XC14RLyOGr",
	"7N7FWW/hbOiqAD6sOHpkP8/3vffanv2LTOImOcLgnAt2HdWLmCdvjzlXvHWVJvlXHOJv/4tCp8ohKV6z",
	"GdIKie0CE3C8tGFgmrgNu2TonexmE/ZYtg1fXbb1q6DzTEo86ib3yEgryZ8wk5v6gPPNLz5zcC/xBh2S",
	"Z/Q48dwixZUKfkNBHswOyW417Y6GA5486NyBYx5DBDos5DsK0Z+8HGHxKnvp1XIo9d7yN1Jx2hwx/YHQ",
	"E/VObXQ2Pnt70M/a/aBb9X/0bQIVcnHox0/IxQsN6UPfqSM/TPRhov7lVyGvXfXk++1TOGZFhcXdMQfV",
	"YTyfn7GrnwYMetRFoG8Dz2i5+Cc7g27R/R0AAP//+6ixaCwNAAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
