// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWwXLTMBD9Fc3C0VhpKRffUqbQDKVlWsqlk4NqbyxRW1KldToh439nVnYItAF6KRd6",
	"8o539d7T7r6x11C61juLliIUa4ilxlal8CgEFzjwwXkMZDC9bjFGVSOHFcYyGE/GWSiGerFJZ0Arj1BA",
	"pGBsDX2fQcDbzgSsoLj6ATPvOWPswjFiY0q0MYFb1fLxqVelRrGfTyCDLjRQgCbysZDy7u4uVymdu1DL",
	"8WyUJ7O3R6cXR6/280muqW2gz4AMNQx35tFeaLMg8dHUQbF0Ma2WJrogTKtqFNNPM8hgiSEO1+pshQtj",
	"sWIY59Eqb6CA1/kk34MMvCKd+iKVN3K5JxOKvF6Ru0Er1+nRyzVfp+e6Gulh794jCdIozr5MRxlLo8Tl",
	"+QkkzkHorBoqZ1xwuPrMyElBUC0ShgjF1X3gy4hB0Fhp+A0LhmzT3k1qOxoKHWbjHrDQB2O8T5HkiIS3",
	"k2LMPJ5hzsXROx4m5/cnE36UzhLa1DzlfWPK1BTplovt4nK0cKFVBAVcG6vCascm9tm9K0zttvM85oM/",
	"Mn6NfOhnypcBF1DAC7k1kxydJAcb7SA9VJU4x9sOIw2ce0/PeWlVR9oF823Y54PJwdOTnjp65zqbCN/8",
	"i87OLGGwqhEXGJYYxKYwA1I1uwSGSc/7DDSq6qEfj1FVjzQkl/6njnw20bOJ+AOegdSoGtK//b4dp7Qo",
	"NZY3uxzUpPX8+46dffhFwcg6/EPEpHOw3PCjIKGf998DAAD//5Ev0OTiCAAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
