// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	externalRef0 "github.com/kubev2v/migration-planner/api/v1alpha1"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/7xUTXPTMBD9K5qFo7HSUi6+pUyBDKXttJRLJwfV2diitqSu1umEjP87s7JDaBsYLuVk",
	"jd7ue0/74Q2Uvg3eoeMIxQZiWWNr0vGEyJMcAvmAxBbTdYsxmgrluMBYkg1svYNiiFdbOANeB4QCIpN1",
	"FfR9BoT3nSVcQHHzi2beC2Ld0gtjY0t0MZE700r6NJiyRnWYTyCDjhoooGYOsdD64eEhNwnOPVV6zI36",
	"dPb+5Ozq5M1hPslrbhvoM2DLjdB9sRUZMawuGuMckrKtqVBNL2aQwQopDo/p3AKX1uFCkn1AZ4KFAt7m",
	"k/wAMgiG61QNbYLVqwOdWPTtmv0dOr1Jn15v5BG9xFXIzyv2EVlxjer823S0sbJGXV+eQtIcjM4WQ+RM",
	"Ao7XX4U5OSDTIiNFKG6eEl9HJMVjpJUbMQzZtqhbaNcQpg6zsfti9FnznkokOyrx7ZUYkX9XmEtwDF5a",
	"KPjhZCKf0jtGl4pnQmhsmYqi/Wq5G1c5LT21hqGAW+sMrffMX589ecLU7SovbT76q+L3KEm/S74mXEIB",
	"r/RuhfS4P3pYnj2ix2ahLvG+w8iD5sHLa14703Htyf4Y5vlocvTyomeeP/jOJcF3/6OyM8dIzjTqCmmF",
	"pLaBGbCpZEtg6PRcrnSNpuH6j6v5KcGqrLG8e7aNAwj7B/Yxz/nnRw5G1eGnF5PPYX+HP5uGft7/DAAA",
	"//8rT6DtkwUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	pathPrefix := path.Dir(pathToFile)

	for rawPath, rawFunc := range externalRef0.PathToRawSpec(path.Join(pathPrefix, "../openapi.yaml")) {
		if _, ok := res[rawPath]; ok {
			// it is not possible to compare functions in golang, so always overwrite the old value
		}
		res[rawPath] = rawFunc
	}
	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
