---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: migration-planner-s3-creds
parameters:
  - name: S3_ACCESS_KEY
    description: Base64-encoded s3 access key
    displayName: S3 access key Base64 Content
    value: dGVzdAo=
  - name: S3_SECRET_KEY
    description: Base64-encoded s3 secret key
    displayName: S3 secret key Base64 Content
    value: dGVzdAo=
objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: migration-planner-s3-creds
    type: Opaque
    data:
      access_key: ${S3_ACCESS_KEY}
      secret_key: ${S3_SECRET_KEY}
