---
kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: vcsim-deployment
parameters:
  - name: APP_NAME
    description: The name of the application.
    required: true
  - name: PORT
    description: The port the application will listen on.
    required: true
  - name: USERNAME
    description: Username for the simulator.
    required: true
  - name: PASSWORD
    description: Password for the simulator.
    required: true
objects:
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        deployment.kubernetes.io/revision: "1"
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
    spec:
      progressDeadlineSeconds: 600
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        matchLabels:
          app: ${APP_NAME}
      strategy:
        rollingUpdate:
          maxSurge: 25%
          maxUnavailable: 25%
        type: RollingUpdate
      template:
        metadata:
          labels:
            app: ${APP_NAME}
        spec:
          containers:
            - name: ${APP_NAME}
              image: docker.io/vmware/vcsim
              imagePullPolicy: Always
              args: ["-l", "0.0.0.0:${PORT}", "-username", "${USERNAME}", "-password", "${PASSWORD}"]
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - name: tmp
                  mountPath: /tmp
          volumes:
            - name: tmp
              emptyDir: {}
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          terminationGracePeriodSeconds: 30
