name: Helm lint
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  helmlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Orchestartor Helm Lint
        run: |
          helm lint charts/migration-cluster-day2
