// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
)

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabW/bOBL+KwT3gLsDZDvt9oCDv6Xpm7F9CZI2+6ENFmNxbHFDkVqSsusr/N8PJCVb",
	"tijZySXdHjafmobkvD4zfIbKN5qqvFASpTV0/I2aNMMc/I+nc5TW/VBoVaC2HP2vU41gkZ36pZnSOVg6",
	"pgwsDizPkSbUrgqkY2qs5nJO14k7wlBaDuKTFu5YawdnO9LKkrOYIGPBlt4KlGVOx5+pVHaQKikxteiO",
	"LIFbLueDmdKDrVpDE4paK00TOgeboRM44JK7xQGXC5RW6RVNaFkMrBo4b2hCjSp1ioO5kkivO82ZyJmK",
	"OlUW7LaRWqA2XMmIuHVCNf5Rco3M+e3jU4Vjx5D9aCeNhDVN2uraeqamv2NqnR0+9+dafV21AZBZW3Tl",
	"0a2ZrkWpNhLbzrVMeAEWjFUa2xYwbm4mLKpjphHPoICU29Xr540tXFqco/ZGgmZL0HiapihQu4C8Uwts",
	"bJ4qJRCk25wrhnF3Cq2sSpX46BciG6yyIA4ZY7tOL1AypQ8jwa+2lbVCsZGY1PHrjsSec3UUYkh56cuq",
	"laIcjYG594yhSTUvrMd12E/q5eSAc/W+63VC33Bj1VxDHgEEWHD/cou56YszBa1h5fPK5RWIEuO7jcUi",
	"trJvXi2kOpEES2JxmsiZhkg3FaWxqM05agf4FKVFfUtXWF0pZufg3zTO6Jj+NNp2+FHV3kfb4orIy5Sx",
	"52qJ+tKCDUKBMe4SCOJ8x/xO47aOO2nOvbPg6S19k2iXSt8c79n7cCAmK5RIFfAO9W7LNhF9u944v47A",
	"SGNzRP6+VUkHItpxbOepEa0dUMThWN95LUjyGql9YQ5wdm1qC9m+/VdnYZs7cTiJV+9MK46LTSScgKQy",
	"M+bbW5iGlr3r1w2u4o12rw10tCJ3vN4c0/qOzzW4GpkYU0YuLTAGjckrTtXmSKrcWWnATdT+9BsYtiVN",
	"RbXYw/YeX2B7fkbqrC7BdptemCW3aRZnB5B3XKPVDVlTPmNBMtAsXGRW82kZuN9GfEJLacqiUNotxJjb",
	"QoCMMoj45eptiwXx0jPESLJr7twXyUCw18ldKPWRhJk3y7y/nuuNNeCOR0Sot1jz7kqpkucac252LpEG",
	"6bo1c46xY6+9m/42bOjO7Jk/HLm23Y8znoLFswy4vB2ii5oGH0RHIMyOkJjsvJwKnv6Cq8OwPYDXt9zY",
	"o7NbQTyS3rDyycf0g49mRyFMHg6s+4lvjHK16mgcNoPkLjsNvyfcECAabakl8R2fzJQmKQhhiM3AEqbk",
	"3229Q7mBkgThZhjI8zFU+JRkZQ5yoBEYTAWSxjJRM2IzJGGyC//jhji5vvkOYwHUCCYMj/uKckgzLrFT",
	"1TJb7SlwMeDS2/CFvgIuSo1faGXPkEwqg0J0uCGYF9bJQO3/KxXhMmTcCYMFcOEUD8kpufBmklSA5jOO",
	"hoAkbz5+PK+dTRVDMi1dlNFJskQtUGvOkHA77H8XiKaziuU2eOSDRKJmY/KFXpZpisZ8oUTppqdD8k45",
	"V+RMjYkfa8ej0Zzb4c2/zZArB8u8lNyuRqmS4RJS2owYLlCMDJ8PQKcZt5jaUuMICj5IlQcnV9IMc/aT",
	"KTAdgGSDzRR/xFBc06g2aWNHvRnEauHq3QWGl47nGuGGqaWMDP3N4auvNrdTWk2Uezj0K6UDnXDQOHbf",
	"r9xmv4KWXM5N/5n3yvaL3wvQ1sna9KidB43qsiAefRO5XoryrJ7n+nlyO3XrMN+f1XzyjufDe8UdDuc1",
	"P2zm6J6YpWyGM7SR+xSv/tdZV20eA7uE9BlYnY4JLu5tHNeQ3zm1h8r5qFo+vpBjgzRtq0q25VK7t4Fw",
	"sxZ8fjc52o1pB7RiaL7uzftuHW+HkAjN3XMvNrA0AKDR8LlENih1ZLbFrwXXaH4DG3lxc2vhGnbk2VMZ",
	"dx1+unhLrLpBzyWOmzoq3bvyzzUOgm1epBPvACMUMC7ngcV4LBHGTequ8hXhOcxxeJDHO33taKw9Vwzx",
	"FjxFaTzeAt2mpwWkGZKnwxNaGUzr63u5XA7BLw+Vno+qs2b0dnL28v3ly8HT4ckws3mYZbh1MN6OyeRc",
	"gJSoyen5pPF6PqalZDjjEplHQoESCk7H9OfhyfCJgxnYzOfIkYDR4skoBKNiKwJthBmG3xMgqRIC05ql",
	"1Se9mqqXMTqmL/z2y82qRlMoWU1XT09O/JWipK1mUigK4UYXruTo94owhso/OAsEquIzsGvxh1+c989O",
	"ntybrvCwHFH1SUJpM6X5f0LI/3WPDnYqnTjaJUEQrHYk1IJrW5+rr0T+iXqOkfpz01Zn6tziNnEFaMgx",
	"PDx+3pfjeaYSZJmBxQWGImY4g1K4UcQ1D2IyVQpGpkiAMWTEKr9LoymF9Y9mdEz/KNEPSFXBcJmKkuFv",
	"lSiaNGLV6lnXD4mu7XD6IyEsnupCmUiuw3sBgSrfrXSH9ct60fU6NPa5Yqt7jmL1cLHe7ahWl7huZfDJ",
	"PeuOhTTYw0IKv0O9PgdGLkJ0HxvTOtm/fEbfOFv33UAv6huoA8jNK+dQ45q82Lxm1Pt9H3I3Y6MNMboP",
	"1WYnOvB69B0aU19T+osg+tnJzw+v9JXSU84YyqDx2cNrfK/sK1XK71e0W4W34BGv0YYiKjDlM46sqzZf",
	"o30szMfCfCzMh6L5RRkpz/AdZHNjkplWOdl8jyAzLtqVGs78aMX6UJx050vRUcz0e3SKU0k+XJ2GF4nH",
	"nvHYM+7eMy5Ru7H85a2J+CiAb/yNZgis3VreIDBf+Vug7ncSt2VSrfS3Efbn3fk9V/Qx5XEUnA/D7yBc",
	"bpvekJED2a3fbXup3Sa/ZMGBfLp4283tXlRPrGFTb8rDAeIz9f/F73ZfvWM9zb9hb96b/7Kd/NmfNLMc",
	"gr5eWKXCnxIdRZqmK1IW9ZcDkOTi6qM779kTYVxjasUqQqPckYug61UgWj84l8pLYXkB2o6cmEH9B8xb",
	"6bvfdzx7bEXvY4a7EfrHy68pin82v+dMuQT/2tv/pcUriH9quV+S1vm3MQf/+iFCLpzPAS9uGg5/yTEr",
	"hVg9ErlHIvfQRC5DEDbrvNPDMkkzTG9idE34VnMcTWqYUGm99vYbb2jocOFT54iur9f/DQAA//+M5kqv",
	"1TUAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
