openapi: 3.0.1
info:
  title: Migration Planner API - agent endpoint
  version: undefined
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
servers:
  - url: /
paths:
  /api/v1/sources/{id}/status:
    put:
      tags:
        - source
      description: replace status of the specified source
      operationId: replaceSourceStatus
      parameters:
        - name: id
          in: path
          description: ID of the source
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SourceStatusUpdate'
        required: true
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '../openapi.yaml#/components/schemas/Source'
        "400":
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '../openapi.yaml#/components/schemas/Error'
        "401":
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '../openapi.yaml#/components/schemas/Error'
        "404":
          description: NotFound
          content:
            application/json:
              schema:
                $ref: '../openapi.yaml#/components/schemas/Error'
  /health:
    get:
      tags:
        - health
      description: health check
      operationId: health
      responses:
        "200":
          description: OK

components:
  schemas:
    SourceStatusUpdate:
      type: object
      properties:
        status:
          type: string
        statusInfo:
          type: string
        inventory:
          $ref: '../openapi.yaml#/components/schemas/Inventory'
        credentialUrl:
          type: string
      required:
        - status
        - statusInfo
        - credentialUrl
