// Package v1alpha1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.3.0 DO NOT EDIT.
package v1alpha1

// SourceStatusUpdate defines model for SourceStatusUpdate.
type SourceStatusUpdate struct {
	Inventory  string `json:"inventory"`
	Status     string `json:"status"`
	StatusInfo string `json:"status_info"`
}

// ReplaceSourceStatusJSONRequestBody defines body for ReplaceSourceStatus for application/json ContentType.
type ReplaceSourceStatusJSONRequestBody = SourceStatusUpdate
