{
 "title": "assisted_migrations_test",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "API overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability (selected time) ",
   "type": "stat",
   "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(chi_requests_total{service=\"migration-planner-metrics\",code!~\"5..|0\"}[$__range]))\n/\nsum(increase(chi_requests_total{service=\"migration-planner-metrics\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "Number of requests per second based on response code",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(chi_requests_total{service=\"migration-planner-metrics\",path!~\"/health\"}[$__range]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Number of requests per second based on response code",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "sum(rate(chi_requests_total{service=\"migration-planner-metrics\", code!~\"2..\"}[$__range])) / sum(rate(chi_requests_total{service=\"migration-planner-metrics\"}[$__range]))",
     "legendFormat": "non 2xx"
    },
    {
     "expr": "sum(rate(chi_requests_total{service=\"migration-planner-metrics\", code=~\"5.0\"}[$__range])) / sum(rate(chi_requests_total{service=\"migration-planner-metrics\"}[$__range]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\", code!~\"5..|0\"}[5m])))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\", code!~\"5..|0\"}[5m])))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\", code!~\"5..|0\"}[5m])))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Latency (<300ms)",
   "type": "stat",
   "description": "The percentage of time that the API responds within 300ms.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\", code!~\"5..|0\",le=\"300\"}[$__range]))\n/\nsum(increase(chi_request_duration_milliseconds_count{service=\"migration-planner-metrics\", code!~\"5..|0\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Agent API overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Availability (selected time) ",
   "type": "stat",
   "description": "The percentage of time that the API is available (not returning 500 Internal Service Errors).",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(chi_requests_total{service=\"migration-planner-metrics\", exported_service=\"agent_server\",code!~\"5..|0\",path!~\"/health\"}[$__range]))\n/\nsum(increase(chi_requests_total{service=\"migration-planner-metrics\",exported_service=\"agent_server\",path!~\"/health\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "timeseries",
   "description": "Number of requests per second based on response code",
   "gridPos": { "h": 8, "w": 7, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(chi_requests_total{service=\"migration-planner-metrics\", exported_service=\"agent_server\",path!~\"/health\"}[$__range]))",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "timeseries",
   "description": "Number of requests per second based on response code",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(chi_requests_total{service=\"migration-planner-metrics\", exported_service=\"agent_server\",path!~\"/health\", code!~\"2..\"}[$__range])) / sum(rate(chi_requests_total{service=\"migration-planner-metrics\", exported_service=\"agent_server\",path!~\"/health\"}[$__range]))",
     "legendFormat": "non 2xx"
    },
    {
     "expr": "sum(rate(chi_requests_total{service=\"migration-planner-metrics\", exported_service=\"agent_server\",path!~\"/health\", code=~\"5..0\"}[$__range])) / sum(rate(chi_requests_total{service=\"migration-planner-metrics\", exported_service=\"agent_server\",path!~\"/health\"}[$__range]))",
     "legendFormat": "5xx"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "description": "The request duration within which the API have served 99%, 95%, 50% of requests",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\", exported_service=\"agent_server\", code!~\"5..|0\"}[5m])))",
     "legendFormat": "99th"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\", exported_service=\"agent_server\", code!~\"5..|0\"}[5m])))",
     "legendFormat": "90th"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\", exported_service=\"agent_server\", code!~\"5..|0\"}[5m])))",
     "legendFormat": "50th"
    }
   ]
  },
  {
   "title": "Latency (<300ms)",
   "type": "stat",
   "description": "The percentage of time that the API responds within 300ms.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(chi_request_duration_milliseconds_bucket{service=\"migration-planner-metrics\", exported_service=\"agent_server\", code!~\"5..|0\",path!~\"/health\",le=\"300\"}[$__range]))\n/\nsum(increase(chi_request_duration_milliseconds_count{service=\"migration-planner-metrics\", exported_service=\"agent_server\", code!~\"5..|0\",path!~\"/health\"}[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Agent metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Agents in up-to-date state",
   "type": "stat",
   "description": "Current number of agents in up-to-date state",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (service) (assisted_migration_agent_status_count{state=\"up-to-date\",service=\"migration-planner-metrics\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Agents in gathering-inventory state",
   "type": "stat",
   "description": "Current number of agents in gathering-inventory state",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (service) (assisted_migration_agent_status_count{state=\"gathering-initial-inventory\", service=\"migration-planner-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Histograme of agents' states",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 6, "y": 19 },
   "targets": [
    {
     "expr": "max by (state) (assisted_migration_agent_status_count{service=\"migration-planner-metrics\", state!=\"\"})",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Agents in waiting-for-credential state",
   "type": "stat",
   "description": "Current number of agents in waiting-for-credential state",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (service) (assisted_migration_agent_status_count{state=\"waiting-for-credentials\", service=\"migration-planner-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Agents in error state",
   "type": "stat",
   "description": "Current number of agents in error state",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (service) (assisted_migration_agent_status_count{state=\"error\", service=\"migration-planner-metrics\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}