{
 "title": "Service Dashboards",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "No of customers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "assisted_migration_inventory_customers_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No of VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "assisted_migration_inventory_vms_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No of Discovery reports",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "assisted_migration_inventory_inventories_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "No of Operating Systems",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (group(assisted_migration_inventory_vms_by_os_total) by (os))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Top 5", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Top Operatating Systems",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, assisted_migration_inventory_vms_by_os_total)",
     "legendFormat": "{{os}}"
    }
   ]
  },
  {
   "title": "Top 5 customers by number of VMs",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 8, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, assisted_migration_inventory_vms_by_customer_total)",
     "legendFormat": "{{org_id}}"
    }
   ]
  },
  {
   "title": "Top 5 customers by total storage",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (org_id) (assisted_migration_inventory_storage_by_customer_total))",
     "legendFormat": "{{org_id}}"
    }
   ]
  },
  { "title": "VMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "VMs by Operating System",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "targets": [
    {
     "expr": "sort_desc(assisted_migration_inventory_vms_by_os_total)",
     "legendFormat": "{{os}}"
    }
   ]
  },
  {
   "title": "VMs by customer",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "targets": [
    {
     "expr": "sort_desc(assisted_migration_inventory_vms_by_customer_total)",
     "legendFormat": "{{org_id}}"
    }
   ]
  },
  {
   "title": "Storage by customer",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "sort_desc(assisted_migration_inventory_storage_by_customer_total)",
     "legendFormat": "{{org_id}}"
    }
   ]
  }
 ]
}