{
 "title": "Service Dashboards",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "pod",
    "label": "Pod",
    "query": {
     "query": "label_values(assisted_migration_inventory_customers_total,pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "# No of customers",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "options": {
    "content": "Number total of customers including those without any assestements."
   }
  },
  {
   "title": "No of customers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (service) (assisted_migration_inventory_customers_total{service=\"migration-planner-metrics\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "# No of assesments",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 1 },
   "options": {
    "content": "Number total of assestements including the assestements without any inventory."
   }
  },
  {
   "title": "No of assessments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (service) (assisted_migration_inventory_assessments_total{service=\"migration-planner-metrics\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "# No of vms",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 6 },
   "options": {
    "content": "Total number of vm of all customers."
   }
  },
  {
   "title": "No of VMs",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (service) (assisted_migration_inventory_vms_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# No of incomplete assesments",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 6 },
   "options": {
    "content": "Number of incomplete assestements means that the assestement does not have an inventory."
   }
  },
  {
   "title": "No of incomplete assesments",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (service) (assisted_migration_inventory_assessments_total{service=\"migration-planner-metrics\"}) - max by (service) (assisted_migration_inventory_inventories_total)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "# No of Operating System",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 11 },
   "options": {
    "content": "Number of distinct operating systems."
   }
  },
  {
   "title": "No of Operating Systems",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 5, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count (group(assisted_migration_inventory_vms_by_os_total) by (os))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "# No of Discovery Reports",
   "type": "text",
   "gridPos": { "h": 5, "w": 5, "x": 8, "y": 11 },
   "options": {
    "content": "Total number of discovery reports from all the customers."
   }
  },
  {
   "title": "No of Discovery reports",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 11 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (service) (assisted_migration_inventory_inventories_total)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Top 5", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Top Operatating Systems",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (os) (assisted_migration_inventory_vms_by_os_total) / 3)",
     "legendFormat": "{{os}}"
    }
   ]
  },
  {
   "title": "Top 5 customers by number of VMs",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 8, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, (max by (org_id) (assisted_migration_inventory_vms_by_customer_total{service=\"migration-planner-metrics\"})))",
     "legendFormat": "{{org_id}}"
    }
   ]
  },
  {
   "title": "Top 5 customers by total storage",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 7, "x": 15, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(5, sum by (org_id) (assisted_migration_inventory_storage_by_customer_total))",
     "legendFormat": "{{org_id}}"
    }
   ]
  },
  { "title": "VMs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "VMs by Operating System",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "expr": "sort_desc(sum by (os) (assisted_migration_inventory_vms_by_os_total{}) / 3)",
     "legendFormat": "{{os}}"
    }
   ]
  },
  {
   "title": "VMs by customer",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "expr": "max by (service,org_id) (assisted_migration_inventory_vms_by_customer_total{namespace=\"assisted-migration-stage\"})",
     "legendFormat": "{{org_id}}"
    }
   ]
  },
  {
   "title": "Storage by customer",
   "type": "table",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "targets": [
    {
     "expr": "max by (org_id,type) (assisted_migration_inventory_storage_by_customer_total{service=\"migration-planner-metrics\"})",
     "legendFormat": "{{org_id}}"
    }
   ]
  }
 ]
}