-- +goose Up
-- +goose StatementBegin
CREATE TABLE zed_token (
    id SMALLINT PRIMARY KEY,
    token TEXT NOT NULL
);

CREATE TABLE relationships (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relation_id VARCHAR(100) NOT NULL,
    assessment_id VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT NOW(),
    relation_type VARCHAR(50) NOT NULL,
    subject_id VARCHAR(255) NOT NULL,
    subject_type VARCHAR(50) NOT NULL
);

CREATE INDEX relationships_relation_id_idx ON relationships (relation_id);
CREATE INDEX relationships_assessment_id_idx ON relationships (assessment_id);
-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin
DROP TABLE zed_token;
DROP TABLE relationships;
DROP INDEX relationship_id;
-- +goose StatementEnd
