graph TB
    User((User))
    Service[Migration Assessment]
    AgentUI[Agent UI]
    OVA[OVA Image]
    Agent[Agent]
    VCenter[(vCenter)]
    AI[Assisted installer]
    
    subgraph Console-Dot
        AI
        Service
    end

    subgraph vCenter
        VCenter
        subgraph Agent VM OVA
            AgentUI
            Agent
        end
    end
    
    User-->| 1 - Create OVA| Service
    Service-->|2 - Generates OVA| OVA
    User<-->|3 - Downloads OVA| OVA
    User-->|4 - Deploy OVA to| vCenter
    Agent-->|5 - Registers with| Service
    User-->|6 - Enter vCenter credentials| AgentUI
    AgentUI-->|7 - Execute collection of data | Agent
    Agent<-->|8 - Fetch infrastructure data| VCenter
    Agent-->|9 - Sends data to| Service
    Service-->|10 - Create cluster | AI

    classDef service fill:#f96,stroke:#333,stroke-width:2px
    classDef ui fill:#9cf,stroke:#333,stroke-width:2px
    classDef agent fill:#9f9,stroke:#333,stroke-width:2px
    classDef infra fill:#fcf,stroke:#333,stroke-width:2px
    
    class Service service
    class Agent agent
    class VCenter infra
